print("Hola Mundo")
print("hola"+'mundo')
print(555)
print("hola \'mundo\'")
print("estas son dos lineas"+"linea 1 \n linea 2")
print("550+5 es igual a =",550+5)
print("como poner un apostrofe\' para tenerlo")
print("asi se hace una barra invertida\\")